name: Deploy to EC2

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Copy files to EC2
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no Dockerfile index.html ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/

      - name: SSH and deploy on EC2
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ubuntu
            docker stop test-app || true
            docker rm test-app || true
            docker build -t test-app .
            docker run -d -p 80:80 --name test-app --restart unless-stopped test-app
          EOF