name: Terraform Create EC2 and Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Terraform Init
        run: terraform init

      - name: Check if SG exists and import if needed
        id: import_sg
        run: |
          SG_ID=$(aws ec2 describe-security-groups \
            --filters Name=group-name,Values=allow_ssh_http_https \
            --query 'SecurityGroups[0].GroupId' \
            --output text)

          if [ "$SG_ID" != "None" ]; then
            echo "Importing existing SG $SG_ID"
            terraform import aws_security_group.allow_ssh_http_https $SG_ID || true
          else
            echo "No existing SG found. Terraform will create it."
          fi

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
